---
# chocomilk vars

# Package Changelog
changelog: 'https://shop.crealogix.com/software-updates/pm-office5.html'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('.*Aktuelle Version.*') |
  regex_search('\\d.\\d.\\d.\\d\\b')
  }}"

# Download URL
url: 'https://shop.crealogix.com/download/get/file/pm5.office'
# url64:

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*checksumZip\s*=\s*)('.*')
      replace: '$checksumZip = "{{ file_hash }}"'

# readme to description
readme:
  start: 5
  end: 13

# deploy
deploy:
  - provider: chocolatey
    repository: 'https://nuget.itigo.tech/upload'
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: chocolatey
    repository: 'https://push.chocolatey.org/'
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: 'itigo-bot'
    email: 'chocomilk@itigo.ch'
    url: github.com/itigoag/chocolatey.crealogix-paymaker-office.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://matters.itigo.tech'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'software-packages'
